image: node:latest

default:
    tags:
        - "node-latest"

stages:
    - build
    - test

cache:
    paths:
        - node_modules/

install:
    stage: build
    script:
        - npm install
        - npm run lint
    artifacts:
        paths:
            - node_modules/

test:
    stage: test
    script:
        - wget -q http://georgms.github.io/textsearch102/files/simple-wikipedia.zip && unzip -q simple-wikipedia.zip
        - npm run test-ci
    artifacts:
        when: always
        reports:
            junit:
                - junit.xml
